### ISSUE TITLE
Broken dropbox link

### ISSUE THREAD

**Issue by eschluntz** [mauriliodc/thin_astra#3]
The dropbox link to download Orbbec's custom Openni2 in readme.md is broken. Is there another place to download the package? Thanks!

**Comment by mauriliodc** [comment]
Yes, they changed something, you can find the latest binaries here 
[ORBBEC DROPBOX](https://www.dropbox.com/sh/p2uowlt3swdrfno/AACfEbv7ejIU-4FHy4Fyi0ZWa?dl=0)
